language: python
python:
- 3.4
- 2.7

env:
  - QA
  - PROD
script:
   - mkdir ShortStory
   - touch kkk
   - echo 5
   
matrix:
fast_finish: true
  allow_features:
  - python 2.7
  
  exclude:
  - python: 3.4
    env: QA
  
